/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package io.github.andrewdolge.artifactgenerator;

import org.junit.Test;

import io.github.andrewdolge.artifactgenerator.Artifact.ArtifactBuilder;

import static org.junit.Assert.*;

public class ArtifactTest {

    /**
     * Create an Artifact with no Descriptors.
     * 
     */
    @Test public void testArtifactBuilder() {
        
        ArtifactBuilder builder = new ArtifactBuilder();

        Artifact a = builder.build();

        assertNotNull("Artifact with no Descriptors should not be null", a );
    }
}
